# required packages from pip
# - mkdocs
# - mkdocs-material
# - pymdown-extensions
# - mkdocs-macros-plugin
# - mkdocs-bibtex


site_name: Dymos

theme:
  name: material
  palette:
    scheme: "default"
    primary: "blue grey"
    accent: "blue"

plugins:
  - search
  - bibtex:
      bib_file: "references.bib"
      cite_style: "pandoc"
  - macros

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.tabbed
  - pymdownx.superfences
  - codehilite:
      linenums: true

nav:
    - 'index.md'
    - 'Getting Started':
        - 'getting_started/collocation.md'
        - 'getting_started/transcriptions.md'
    - 'Examples and Tutorials':
        - 'examples/examples.md'
        - 'Intro to Dymos':
            - 'examples/intro_to_dymos/intro_ivp.md'
            - 'examples/intro_to_dymos/intro_segments.md'
        - 'examples/brachistochrone/brachistochrone.md'
        - 'examples/vanderpol/vanderpol.md'
        - 'examples/commercial_aircraft/commercial_aircraft.md'
        - 'examples/double_integrator/double_integrator.md'
        - 'examples/hypersensitive/hypersensitive.md'
        - 'examples/finite_burn_orbit_raise/finite_burn_orbit_raise.md'
        - 'examples/min_time_climb/min_time_climb.md'
        - 'examples/multi_phase_cannonball/multi_phase_cannonball.md'
        - 'examples/multibranch_trajectory/multibranch_trajectory.md'
        - 'examples/reentry/reentry.md'
        - 'examples/ssto_earth/ssto_earth.md'
        - 'examples/ssto_moon_linear_tangent/ssto_moon_linear_tangent.md'
        - 'examples/ssto_moon_polynomial_controls/ssto_moon_polynomial_controls.md'
    - 'Dymos API Reference':
        - 'api/run_problem.md'
        - 'api/phase_api.md'
        - 'api/trajectory_api.md'
        - 'api/transcriptions_api.md'
    - 'Contributing':
        - 'contributing/contributing.md'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

use_directory_urls: false
